import Head from 'next/head'
import Image from 'next/image'
import { useEffect, useState } from 'react'
import { IMilk, fetchMilks } from '@/apicalls/milk'
import { Header, Icon } from 'semantic-ui-react'
import MilkContent from '@/components/MilkContent'
import TypeFilter from '@/components/TypeFilter'


export default function Home() {

  const [filterValue, setFilterValue] = useState('all');
  const filterChanged = (value: string) => {
    setFilterValue(value);
  }
  const [milks, setMilks] = useState<IMilk[]>([]);

  useEffect(() => {
    fetchMilks(setMilks);
  }, []);

  const [open, setOpen] = useState(false);
  const [errMessage, setErrMessage] = useState<string>("");


  return (
    <>
      <Head>
        <title>Milk App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <main className="home-main">
        <Header className="home-header" as='h1' icon textAlign='center' inverted color='pink'>
          <Header.Content>The Milk Store</Header.Content>
        </Header>
        <div className="home-filter">
        <TypeFilter filterChanged={filterChanged} />
        </div>
        <div className="home-contents-container">
          <MilkContent milks={milks} filterValue={filterValue} />
        </div>
      </main>
    </>
  )
}
